#!/usr/bin/env python3
# coding: utf-8
"""Validate reviewed UI dictionaries and generate offline platform resources."""
from pathlib import Path
import argparse, collections, json, re, xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = ('zh', 'ko', 'ja', 'de', 'fr', 'es')
TOKENS = re.compile(r'\{\d+\}|%(?:\d+\$)?[sdif]|%%')
def android_decode(text):
    return text.replace("\\'", "'").replace('\\"', '"').replace('\\n', '\n')
def android_encode(text):
    return text.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"').replace('\n', '\\n').replace('@', '\\@').replace('?', '\\?')
def translated(data, english):
    if english in data:
        return data[english]
    # Release notes are composed from reviewed individual bullet translations.
    lines = english.splitlines()
    if lines and all(line.startswith('• ') and line[2:] in data for line in lines):
        return '\n'.join('• '+data[line[2:]] for line in lines)
    raise ValueError(f'Missing translation: {english}')
def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); parser.add_argument('--ios-root', type=Path)
    args = parser.parse_args()
    source = json.loads((ROOT/'docs/locales/source.json').read_text())
    keys = set(source['strings']); dictionaries = {}
    for lang in LANGUAGES:
        path = ROOT/f'docs/locales/{lang}.json'; data = json.loads(path.read_text())
        missing = keys-set(data); extra = set(data)-keys
        if missing or extra: raise SystemExit(f'{lang}: missing {len(missing)}, extra {len(extra)}; {sorted(missing)[:8]}')
        for key, value in data.items():
            if not isinstance(value, str) or not value.strip(): raise SystemExit(f'{lang}: empty translation: {key}')
            if collections.Counter(TOKENS.findall(key)) != collections.Counter(TOKENS.findall(value)): raise SystemExit(f'{lang}: changed placeholders: {key} -> {value}')
            if re.fullmatch(r'https?://\S+|[\w./-]+\.(?:png|jpg|jpeg|svg)',key) and value != key:
                raise SystemExit(f'{lang}: changed resource path or URL: {key}')
        dictionaries[lang] = data
    generated = {}
    # Include only UI strings; no source-language keys, audio, credentials or model weights.
    blob = json.dumps(dictionaries, ensure_ascii=False, separators=(',', ':'))
    generated[ROOT/'desktop/ui/guide/locales.json'] = blob+'\n'
    generated[ROOT/'desktop/ui/guide/locales.js'] = '// Generated by scripts/build-ui-locales.py; edit docs/locales/*.json.\n'+ 'globalThis.SOLFLOW_LOCALES = '+blob.replace('<','\\u003c').replace('\u2028','\\u2028').replace('\u2029','\\u2029')+';\n'
    template = ET.parse(ROOT/'app-android/app/src/main/res/values-en/strings.xml')
    for lang, data in dictionaries.items():
        resources = ET.Element('resources')
        for original in template.getroot():
            if original.tag not in ('string','plurals','string-array'): continue
            node = ET.SubElement(resources,original.tag,original.attrib)
            if original.tag == 'string':
                english = android_decode(''.join(original.itertext()))
                node.text = android_encode(translated(data,english) if original.get('translatable')!='false' else english)
            else:
                for old in original:
                    item = ET.SubElement(node,old.tag,old.attrib)
                    english = android_decode(''.join(old.itertext())); item.text = android_encode(translated(data,english))
        ET.indent(resources,space='    ')
        generated[ROOT/f'app-android/app/src/main/res/values-{lang}/strings.xml'] = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated; edit docs/locales/'+lang+'.json. -->\n'+ET.tostring(resources,encoding='unicode')+'\n'
    if args.ios_root:
        generated[args.ios_root/'app-ios/SolFlow/UI/ui-locales.json'] = blob+'\n'
    for path,text in generated.items():
        if args.check:
            if not path.exists() or path.read_text()!=text:raise SystemExit(f'Out of date: {path}')
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text,encoding='utf-8')
    print(f'PASS: {len(keys)} keys × {len(dictionaries)} languages, placeholders and {len(generated)} generated resources')
if __name__=='__main__': main()
